//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupChat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int Id_Chat { get; set; }
        public int Sender_Id { get; set; }
        public int Chatroom_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
    
        public virtual Chatroom Chatroom { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
